############################################
##########  DICOM TO BIDS SCRIPT  ##########
##########    PENLab Mar 2026     ##########
############################################

import os
import importlib.util
import datetime
import shutil
import re
from pathlib import Path
import subprocess
import sys

# Import meta functions

spec = importlib.util.spec_from_file_location(
    "copy_dicoms_from_disk",
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "scripts", "01_copy_dicoms_from_disk.py")
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

meta_create = mod.meta_create
meta_func = mod.meta_func

def list_folders(path):
    """Return a list of folder (subjects) names in the given directory."""
    if not os.path.exists(path):
        print(f"Error: The path '{path}' does not exist.")
        return []
    
    return [name for name in os.listdir(path) if os.path.isdir(os.path.join(path, name))]

def overlap_dicom_bids(dicom_list, bids_path, bids_list, msg=""):
    """This function checks if there is any subject overlap between the DICOM source folder
    with the temporary and archive BIDS directories. Asks if an overwriting is desired."""

    # Identify subjects that do not need processing
    intersection_bids_list = {
                                sub for sub in dicom_list
                                if re.sub(r'[^a-zA-Z0-9]', '', sub) in bids_list
                                }
    
    # If there are no subjects in both dicoms_folders and bids_path
    if not intersection_bids_list:                                             
        todo_dicoms = dicom_list
        return todo_dicoms

    # If there are subjects in both dicoms_folders and bids_path
    else:
        while True:
            overwrite_bids = input(f"{intersection_bids_list} already in BIDS {msg}directory, overwrite? (Y/N) ").upper()

            # No overwriting: todo_dicoms = dicoms in list not in bids_path
            if overwrite_bids == "N":                                                 
                todo_dicoms = {
                                sub for sub in dicom_list
                                if re.sub(r'[^a-zA-Z0-9]', '', sub) not in bids_list
                                }
                print("Skipped overwriting of " + str(intersection_bids_list) + ".")
                return todo_dicoms

            # Overwriting: delete BIDS in conflict, convert the entire list    
            elif overwrite_bids == "Y":                                                
                for dicom_id in intersection_bids_list:
                    bids_id = re.sub(r'[^a-zA-Z0-9]', '', dicom_id)
                    sub_path = os.path.join(bids_path, f"sub-{bids_id}")
                    heu_path = os.path.join(bids_path, ".heudiconv", bids_id)

                    if os.path.exists(sub_path):
                        shutil.rmtree(sub_path)
                        print(f"INFO: {sub_path} will be overwritten.")

                    if os.path.exists(heu_path):
                        shutil.rmtree(heu_path)
                        print(f"INFO: {heu_path} will be overwritten.")

                todo_dicoms = dicom_list
                return todo_dicoms
            
            else:
                print("Please, enter a valid response. (Y/N)\n") 

def generate_dicom_sub_list(dicoms_path, bids_path, temp_bids_path):
    """This function asks if you want to convert a custom set of subs, otherwise a sub list is automatically generated"""
    # List of DICOMS in input directory 
    dicoms_folders = set(list_folders(dicoms_path))

    # Determine processed subs in BIDS (archive)
    bids = [s[4:] for s in os.listdir(bids_path) if ((s[:4] == "sub-"))]

    # Determine processed subs in BIDS (workspace)
    bids_temp = [s[4:] for s in os.listdir(temp_bids_path) if ((s[:4] == "sub-"))]


    value_ok = False
    while value_ok == False:
        # Automatic or manual list
        manual_list = input("Do you want to specifically convert a custom set of subs? Otherwise, sub list will be autogenerated from input and output folders. (Y/N) ").upper()
    
        if manual_list == "N":

            # Identify subjects needing processing
            todo_dicoms = {
                            sub for sub in dicoms_folders
                            if re.sub(r'[^a-zA-Z0-9]', '', sub) not in bids
                            and re.sub(r'[^a-zA-Z0-9]', '', sub) not in bids_temp
                        }
            value_ok = True

        elif manual_list == "Y":

            dicoms_list_txt = meta_func("dicom_list", "your list of DICOMS file path") 
            with open(dicoms_list_txt) as file:
                dicoms_folders = {
                    os.path.basename(line.strip().rstrip("/"))
                    for line in file
                    if line.strip()
                }

            dicoms_overlap1 = overlap_dicom_bids(dicoms_folders, bids_path, bids)
            dicoms_overlap2 = overlap_dicom_bids(dicoms_overlap1, temp_bids_path, bids_temp, msg="temporary ")
            todo_dicoms = dicoms_overlap2
            value_ok = True
        else:
            print("Please, enter a valid response. (Y/N)")

    todo_dicoms = sorted(todo_dicoms)

    # Print the list of subjects to be processed
    print("Subjects to be processed:", todo_dicoms)

    return todo_dicoms

def delete_scans_events(base_path, glob_pattern, delete_flag, info_msg, warn_name):
    """Delete scans.tsv and events.tsv optional files"""
    files = list(Path(base_path).glob(glob_pattern))

    if not files:
        return

    if delete_flag is True:
        for f in files:
            f.unlink()
        print(f"INFO: {info_msg}")

        if glob_pattern == "sub-*/*scans*":
            os.remove(os.path.join(base_path, "scans.json"))

    elif delete_flag is False:
        print(f"INFO: {warn_name} files were left in place")

    else:
        print(
            f"WARNING: Invalid value for '{warn_name}' variable in heuristics file. "
            f"No deletion of {warn_name} files was done."
        )

def get_dicom_pattern(dicoms_path, subj):
    """Detect the correct DICOM directory depth for a subject."""
    subj_path = Path(dicoms_path) / subj
    
    if not subj_path.exists():
        return os.path.join(dicoms_path, "{subject}", "*", "*", "*", "*", "*")
    
    # Check for DICOM files at different depths (try 6 to 2 wildcards)
    for depth in [6, 5, 4, 3, 2]:
        pattern_parts = [dicoms_path, "{subject}"] + ["*"] * depth
        test_pattern = os.path.join(*pattern_parts)
        test_path = test_pattern.replace("{subject}", subj)
        
        # Use pathlib to check if files exist at this depth
        parent = Path(test_path.split("*")[0]).parent
        if parent.exists():
            files = list(parent.glob(test_path.replace(str(parent), "").lstrip("/")))
            if files:
                return os.path.join(*pattern_parts)
    
    # Default to 5 wildcards if nothing found
    return os.path.join(dicoms_path, "{subject}", "*", "*", "*", "*", "*")

def run_heudiconv(todo_dicoms, temp_bids_path, dicoms_path, heuristic_file_path, logs_path):
    commands = []
    for subj in todo_dicoms:
        try:
            subj_clean = re.sub(r'[^a-zA-Z0-9]', '', subj)
            subj_path = os.path.join(temp_bids_path, f"sub-{subj_clean}")
            os.makedirs(subj_path, exist_ok=True)

            subdir_list = [subdir for subdir in os.listdir(subj_path) if os.path.isdir(os.path.join(subj_path, subdir))]

            # Heuristic must have keys like t1w=create_key('sub-{subject}/anat/sub-{subject}_run-{item:02d}_T1w')        
            # check: Subj folder must be empty
            if not subdir_list:
                print(f"Queuing subject {subj} conversion")
                dicom_pattern = get_dicom_pattern(dicoms_path, subj)
                command = "heudiconv -d "+ dicom_pattern + " -o "+ temp_bids_path +" -f "+ heuristic_file_path +" -s "+ subj +" -c dcm2niix -b --minmeta --overwrite --grouping custom"
                commands.append(command)
            else:
                with open(os.path.join(temp_bids_path, "error_heudiconv.txt"), "a") as f:
                    print(f"WARNING: Subject {subj} was previously processed and will be skipped. Logged in error_heudiconv.txt")
                    f.write(str(datetime.datetime.now()) + "\t" + subj + " already processed\n")
        
        except Exception as e:
            try:
                os.makedirs(temp_bids_path, exist_ok=True)
                with open(os.path.join(temp_bids_path, "error_heudiconv.txt"), "a") as f:
                    print(f"WARNING: Unable to process subject {subj} due to an error. Logged in error_heudiconv.txt")
                    f.write(str(datetime.datetime.now()) + "\t" + subj + " error: " + str(e) + "\n")
            except Exception as err:
                print(f"ERROR: Could not log error for subject {subj}: {err}")
            continue
    
    if not commands:
        print("No subjects to process.")
        return
    
    n = len(commands)
    commands_bash = "\n".join(f'  [{i+1}]="{cmd}"' for i, cmd in enumerate(commands))

    os.makedirs(os.path.dirname(logs_path), exist_ok=True)

    slurm_script = f"""#!/bin/bash
#SBATCH --job-name=heudiconv
#SBATCH --output={logs_path}/slurm_%A_%a_nipype.log
#SBATCH --error={logs_path}/slurm_%A_%a_heudiconv.log
#SBATCH --partition=batch
#SBATCH --cpus-per-task=8
#SBATCH --mem=12G
#SBATCH --array=1-{n}
#SBATCH --time=24:00:00

declare -A COMMANDS=(
{commands_bash}
)

CMD=${{COMMANDS[${{SLURM_ARRAY_TASK_ID}}]}}
echo "Task ${{SLURM_ARRAY_TASK_ID}} running: $CMD"
eval "$CMD"
"""
    result = subprocess.run(["sbatch"], input=slurm_script, text=True, capture_output=True)
    print(result.stdout)  # e.g. "Submitted batch job 12345"

    if result.returncode != 0:
        print("Error:", result.stderr)
        return None
    
    job_id = result.stdout.strip().split()[-1]
    return job_id

def run_cleanup(temp_bids_path, delete_scans, delete_events):

    # .bidsignore file in case error_heudiconv.txt is created
    if os.path.exists(os.path.join(temp_bids_path, "error_heudiconv.txt")):
        if not os.path.exists(os.path.join(temp_bids_path, ".bidsignore")):
            with open(os.path.join(temp_bids_path, ".bidsignore"), "a") as f:
                f.write("error_heudiconv.txt\n")
        else:
            with open(os.path.join(temp_bids_path, ".bidsignore"), "r+") as f:
                lines = {line.rstrip() for line in f}
                if "error_heudiconv.txt" not in lines:
                    f.write("\nerror_heudiconv.txt\n")   

    # Delete *_scans.tsv and *_events.tsv if needed
    delete_scans_events(
        temp_bids_path,
        "sub-*/*scans*",
        delete_scans,
        "Deleting all *_scans.tsv files from each subject folder",
        "*_scans.tsv"
    )

    delete_scans_events(
        temp_bids_path,
        "sub-*/func/*_events.tsv",
        delete_events,
        "Deleting all *_events.tsv files from each subject/func folder",
        "*_events.tsv"
    )

def main():
    # Input paths
    meta_create()
    dicoms_dir = meta_func("dicom", "the path to the temporary workspace DICOMs folder")  # Path to DICOM directories
    bids_dir = meta_func("bids", "the path to the archive BIDS folder")  # Path to shared BIDS directory
    temp_bids_dir = meta_func("bids_ws", "the path to the temporary workspace BIDS folder")  # Path to local BIDS directory
    heuristic_fn = meta_func("heuristic", "your heuristic file path") # Path to heuristic file 
    log_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output", "slurm_logs")

    todo_dicoms = generate_dicom_sub_list(dicoms_dir, bids_dir, temp_bids_dir)

    # Heudiconv run
    job_id = run_heudiconv(todo_dicoms, temp_bids_dir, dicoms_dir, heuristic_fn, log_dir)

    if job_id:
        cleanup_script = f"""#!/bin/bash
#SBATCH --job-name=heudiconv_cleanup
#SBATCH --output={log_dir}/cleanup_%j.log
#SBATCH --error={log_dir}/cleanup_%j.err
#SBATCH --time=01:00:00

source activate generacion-to-bids

python {os.path.abspath(__file__)} cleanup "{temp_bids_dir}" "{heuristic_fn}"
"""
        result = subprocess.run(
            ["sbatch", f"--dependency=afterany:{job_id}"],
            input=cleanup_script,
            text=True,
            capture_output=True
        )

        print(result.stdout)
        if result.returncode != 0:
            print(result.stderr)

if __name__ == '__main__':

    if len(sys.argv) > 1 and sys.argv[1] == "cleanup":
        temp_bids_dir = sys.argv[2]
        heuristic_fn = sys.argv[3]

    # Dynamically load and execute a heuristic module to access configuration settings for processing
        heuristic_module_name = os.path.basename(heuristic_fn).split('.')[0]
        spec = importlib.util.spec_from_file_location(heuristic_module_name, heuristic_fn)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        delete_scans = module.delete_scans
        delete_events = module.delete_events

        run_cleanup(temp_bids_dir, delete_scans, delete_events)
    else:
        main()
